catalog_path = "/Users/omallassi/code/apis-catalog/" 
catalog_dir = "/Users/omallassi/code/apis-catalog/catalog/"

[stash_config]
base_uri = "https://my_stash/rest/api/1.0/projects/my_proj/repos/my_repo"
access_token="cf https://confluence.atlassian.com/bitbucketserver0514/using-bitbucket-server/personal-access-tokens?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash#Personalaccesstokens-usingpersonalaccesstokens";

[server]
bind_adress = "127.0.0.1:8088"
static_resources_path = "/my-static-resource"

[database]
rusqlite_path = "/tmp"