catalog_path = "/Users/omallassi/code/apis-catalog/"
catalog_dir = "/Users/omallassi/code/apis-catalog/catalog/"

[stash_config]
base_uri = "https://my_stash/rest/api/1.0/projects/my_proj/repos/my_repo"
user = "my_username"
pwd = "my_pwd!"